
[build]
command = "npm run build"
## Omit `publish` to allow Netlify's Next.js runtime to handle dynamic routes and output
## See: https://www.netlify.com/blog/2020/11/30/how-to-deploy-next.js-sites-to-netlify/

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
